### ISSUE TITLE
module 'magneticod.bencode' has no attribute 'KRPCDict'

### ISSUE THREAD

**Issue by mosquito520** [boramalper/magnetico#107]
Hi, I have issue on 0.60

I've execute git pull to update to latest commit couple times, to follow latest code.
I found that magneticod does not work after 0.50
current commit is 65dc673

My procedure is,
Update, and execute command "pip3.5 install . --user -U" in each folder to upgrade package.
And my python version is 3.5.3, install from tarball
The platform is raspberry pi 2 with raspbian

The log attached as below, that is pretty weird cause error message is
`module 'magneticod.bencode' has no attribute 'KRPCDict'`
But I've checked that bencode has define attribute 'KRPCDict'`

I have no idea why :~
Does anyone know how to fix it?

Thanks
```
pi@raspberrypi:~ $ until magneticod --node-addr 0.0.0.0:45678;do echo "restarting..."; sleep 5; done;
Traceback (most recent call last):
  File "/home/pi/.local/bin/magneticod", line 11, in <module>
    load_entry_point('magneticod==0.6.0', 'console_scripts', 'magneticod')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/.local/lib/python3.5/site-packages/magneticod/__main__.py", line 30, in <module>
    from . import dht
  File "/home/pi/.local/lib/python3.5/site-packages/magneticod/dht.py", line 34, in <module>
    class SybilNode(asyncio.DatagramProtocol):
  File "/home/pi/.local/lib/python3.5/site-packages/magneticod/dht.py", line 155, in SybilNode
    def __on_FIND_NODE_response(self, message: bencode.KRPCDict) -> None:  # pylint: disable=invalid-name
AttributeError: module 'magneticod.bencode' has no attribute 'KRPCDict'
restarting...
^C
pi@raspberrypi:~ $ 
```

**Comment by boramalper** [comment]
Closing since we re-wrote **magnetico** in Go and this problem shall no longer exists. =)
