### ISSUE TITLE
sqlite3.IntegrityError

### ISSUE THREAD

**Issue by blimeybloke** [boramalper/magnetico#116]
So I do have a real bug :)

After the system is running for about 12 hours, I start to see this:
sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash
2017-07-01 01:11:03,366  INFO      Added: `REMOVED[ettv]`
2017-07-01 01:11:03,368  ERROR     Could NOT commit metadata to the database! (24764 metadata are pending)
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/magneticod/persistence.py", line 116, in __commit_metadata
    self.__pending_metadata
sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash
2017-07-01 01:11:05,641  INFO      Added: `REMOVED`
2017-07-01 01:11:05,643  ERROR     Could NOT commit metadata to the database! (24765 metadata are pending)
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/magneticod/persistence.py", line 116, in __commit_metadata
    self.__pending_metadata
sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash

And this goes on in a loop and nothing new ever gets added.  If this was mysql, I would run an optimize or repair but not sure how to do that with sqllite if that is the issue?

**Comment by ad-m** [comment]
Duplicate od #97

**Comment by blimeybloke** [comment]
Thank you, I did not notice it.
