### ISSUE TITLE
magneticow: README.rst can't be decoded as ASCII

### ISSUE THREAD

**Issue by mweinelt** [boramalper/magnetico#127]
Happens on 3a7de3daaf9b27e0b4e0d963b8945a8f6ca24b03

```
$ pip3 install --user -e . 
Obtaining file:///home/magnetico/magnetico/magneticow
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/magnetico/magnetico/magneticow/setup.py", line 13, in <module>
        long_description=read_file("README.rst"),
      File "/home/magnetico/magnetico/magneticow/setup.py", line 6, in read_file
        return file.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3407: ordinal not in range(128)
```

**Comment by mweinelt** [comment]
Probably related to the example passwords:
- staatsbürgerschaft
- bürgerschaft
