### ISSUE TITLE
No such module:fts4

### ISSUE THREAD

**Issue by xeeoon** [boramalper/magnetico#146]
`[root@localhost sqlite-autoconf-3070500]# magneticow --port 8080 --user test test
2017-08-23 12:54:52,053 INFO Connecting to magneticod's database...
Traceback (most recent call last):
File "/root/.local/bin/magneticow", line 11, in 
sys.exit(main())
File "/root/.local/lib/python3.5/site-packages/magneticow/main.py", line 34, in main
magneticow.initialize_magneticod_db()
File "/root/.local/lib/python3.5/site-packages/magneticow/magneticow.py", line 256, in initialize_magneticod_db
magneticod_db.execute("CREATE VIRTUAL TABLE temp.fts_torrents USING fts4(name);")
sqlite3.OperationalError: no such module: fts4`

Python version:3.5.0
Centos 6, and magneticod works fine.

**Comment by boramalper** [comment]
Closing due to irrelevance. Try using the v0.7.0 instead and feel free to open the issue again if your problem persists; which I think is solved. =)
