### ISSUE TITLE
sqlite3.OperationalError: no such table: main.torrents

### ISSUE THREAD

**Issue by alahoo** [boramalper/magnetico#157]
python3.6 and centos 6.8
magneticow --port 8080 --user admin admin
Traceback (most recent call last):
  File "/opt/program/omsapython/bin/magneticow", line 11, in <module>
    sys.exit(main())
  File "/opt/program/omsapython/lib/python3.6/site-packages/magneticow/__main__.py", line 34, in main
    magneticow.initialize_magneticod_db()
  File "/opt/program/omsapython/lib/python3.6/site-packages/magneticow/magneticow.py", line 255, in initialize_magneticod_db
    magneticod_db.execute("CREATE INDEX IF NOT EXISTS discovered_on_index ON torrents (discovered_on);")
sqlite3.OperationalError: no such table: main.torrents

**Comment by scriptzteam** [comment]
does the database exists ? :)

try to specifiy database file path in **magneticod**

**Comment by boramalper** [comment]
Closing as we no longer use Python (but switched to Go). Let me know if you encounter any other issues with more recent versions. =)
