### ISSUE TITLE
Magneticow doesn't start

### ISSUE THREAD

**Issue by Rui-Santos** [boramalper/magnetico#158]
`2018-01-18 15:06:13,705  INFO      Connecting to magneticod's database...
2018-01-18 15:06:13,706  INFO      magneticow is ready to serve!
2018-01-18 15:06:13,707  INFO      Closing magneticod database...
Traceback (most recent call last):
  File "/home/rui/.local/bin/magneticow", line 11, in <module>
    sys.exit(main())
  File "/home/rui/.local/lib/python3.6/site-packages/magneticow/__main__.py", line 38, in main
    http_server.serve_forever()
  File "/home/rui/.local/lib/python3.6/site-packages/gevent/baseserver.py", line 360, in serve_forever
    self.start()
  File "/home/rui/.local/lib/python3.6/site-packages/gevent/baseserver.py", line 304, in start
    self.init_socket()
  File "/home/rui/.local/lib/python3.6/site-packages/gevent/pywsgi.py", line 1450, in init_socket
    StreamServer.init_socket(self)
  File "/home/rui/.local/lib/python3.6/site-packages/gevent/server.py", line 127, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/home/rui/.local/lib/python3.6/site-packages/gevent/server.py", line 138, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/home/rui/.local/lib/python3.6/site-packages/gevent/server.py", line 225, in _tcp_listener
    sock = socket(family=family)
  File "/home/rui/.local/lib/python3.6/site-packages/gevent/_socket3.py", line 81, in __init__
    self._sock = self._gevent_sock_class(family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
`

That's the error it gives. I'm lost on what to do now...

**Comment by scriptzteam** [comment]
Dunno it works well on my end :)

**Comment by donaldsteele** [comment]
what are your startup parameters? If you just run magneticod with no options does it start?
