### ISSUE TITLE
Could NOT commit metadata to the database! (XY metadata are pending)

### ISSUE THREAD

**Issue by gasperko** [boramalper/magnetico#180]
`sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash
2018-11-26 09:51:28,149  INFO      Added: `TORRENT_NAME`
2018-11-26 09:51:28,151  ERROR     Could NOT commit metadata to the database! (38783 metadata are pending)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/magneticod-0.6.0-py3.6.egg/magneticod/persistence.py", line 116, in __commit_metadata
    self.__pending_metadata
sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash
2018-11-26 09:51:28,378  INFO      Added: `TORRENT_NAME`
2018-11-26 09:51:28,380  ERROR     Could NOT commit metadata to the database! (38784 metadata are pending)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/magneticod-0.6.0-py3.6.egg/magneticod/persistence.py", line 116, in __commit_metadata
    self.__pending_metadata
sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash
2018-11-26 09:51:31,531  WARNING   Max. number of neighbours are < 200 and there is still congestion! (check your network connection if this message recurs)
2018-11-26 09:51:32,558  WARNING   Max. number of neighbours are < 200 and there is still congestion! (check your network connection if this message recurs)
2018-11-26 09:51:33,989  INFO      Added: `TORRENT_NAME`
2018-11-26 09:51:33,992  ERROR     Could NOT commit metadata to the database! (38785 metadata are pending)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/magneticod-0.6.0-py3.6.egg/magneticod/persistence.py", line 116, in __commit_metadata
    self.__pending_metadata
sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash
2018-11-26 09:51:35,371  INFO      Peer does NOT support the extension protocol
2018-11-26 09:51:35,931  INFO      Peer rejected us.
2018-11-26 09:51:35,931  INFO      Peer rejected us.
2018-11-26 09:51:35,931  INFO      Peer rejected us.
2018-11-26 09:51:35,931  INFO      Peer rejected us.
2018-11-26 09:51:35,931  INFO      Peer rejected us.
2018-11-26 09:51:35,931  INFO      Peer rejected us.
2018-11-26 09:51:35,931  INFO      Peer rejected us.
2018-11-26 09:51:35,931  INFO      Peer rejected us.
2018-11-26 09:51:35,932  INFO      Peer rejected us.
2018-11-26 09:51:35,932  INFO      Peer rejected us.
2018-11-26 09:51:35,932  INFO      Peer rejected us.
2018-11-26 09:51:35,932  INFO      Peer rejected us.
2018-11-26 09:51:36,057  INFO      Added: `TORRENT_NAME`
2018-11-26 09:51:36,060  ERROR     Could NOT commit metadata to the database! (38786 metadata are pending)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/magneticod-0.6.0-py3.6.egg/magneticod/persistence.py", line 116, in __commit_metadata
    self.__pending_metadata
sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash
2018-11-26 09:51:36,800  INFO      Peer does NOT support the extension protocol
^C2018-11-26 09:51:37,065  CRITICAL  Keyboard interrupt received! Exiting gracefully...
2018-11-26 09:51:37,067  ERROR     Could NOT commit metadata to the database! (38786 metadata are pending)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/magneticod-0.6.0-py3.6.egg/magneticod/persistence.py", line 116, in __commit_metadata
    self.__pending_metadata
sqlite3.IntegrityError: UNIQUE constraint failed: torrents.info_hash
`

I need to restart the magneticod almost everyday

**Comment by ameba23** [comment]
since you are running the python version, i would not expect this to get fixed.

i had the same problem, and as a quick and dirty hack i added the lines:
```python
if len(self.__pending_metadata) > 100:
  sys.exit()
```
to persistence.py (at line 132).

and get magneticod to restart automatically by running it with:

```
until magneticod; do echo "restarting..."; sleep 5; done;
```
This does not really address the problem and for sure there is a better way of fixing it.  but it works for me for now.

**Comment by gasperko** [comment]
Thank you for your quick and spot on reply. I did as you said and now I run it again and hopefully there will not be the same error. Thanks again for your help, much appreciated
