### ISSUE TITLE
Consistent crash on OSX 10.12.4 with Python3.6

### ISSUE THREAD

**Issue by kruel** [boramalper/magnetico#21]
2017-04-10 09:03:45,890  INFO      magneticod v0.2.0 started
2017-04-10 09:03:45,907  DEBUG     SybilNode 85F83B5C0FA7DBC0976599537B191DC1E983A46F on ('0.0.0.0', 0) initialized!
2017-04-10 09:04:09,797  WARNING   Belated TICK! (Δ = 7)
Traceback (most recent call last):
  File "/Users/xxxxxxxx/Library/Python/3.6/bin/magneticod", line 11, in <module>
    sys.exit(main())
  File "/Users/xxxxxxxx/Library/Python/3.6/lib/python/site-packages/magneticod/__main__.py", line 81, in main
    loop()
  File "/Users/xxxxxxxx/Library/Python/3.6/lib/python/site-packages/magneticod/__main__.py", line 154, in loop
    key.fileobj.on_receivable()
  File "/Users/xxxxxxxx/Library/Python/3.6/lib/python/site-packages/magneticod/bittorrent.py", line 112, in on_receivable
    self.__on_bt_handshake(self.__incoming_buffer[:68])
  File "/Users/xxxxxxxx/Library/Python/3.6/lib/python/site-packages/magneticod/bittorrent.py", line 183, in __on_bt_handshake
    msg_dict_dump
TypeError: not all arguments converted during bytes formatting

**Comment by boramalper** [comment]
>> WARNING:
>>
>> Python 3.6.0 and 3.6.1 suffer from a bug (issue #29714) that causes magneticod to fail. As it is an interpreter bug that I have no control on, please make sure that you are not using any of those Python 3 versions to run magneticod.

Read the manual please, it's right there.

**Comment by kruel** [comment]
Boom!  Clearly I missed that. Thanks for the response.
