### ISSUE TITLE
Queston: How do I get this running on windows?

### ISSUE THREAD

**Issue by alexlambson** [boramalper/magnetico#22]
Title. 

Also, if you're looking for contributors. I have a CS degree and experience with distributed systems. I'll need to brush up on my python skills, but I can help if you want it.

**Comment by boramalper** [comment]
Hello Alex,

I never intended to run **magnetico** on Windows but I cannot see any specific reason why it shouldn't work (except requiring a few minor modifications).

We all would be glad to receive your contributions, feel free to contribute in any way you can. Although I cannot be active until 18 May (finals...) I will be happy to check and collaborate. =)

**Comment by alexlambson** [comment]
@boramalper I can't figure out how to get pymodules running on windows. I'll check in once I figure it out. Good luck with class, friend! :)

**Comment by perfectdark123** [comment]
If you have Windows 10, then activate the windows-subsystem for Linux. There you can install it, just like in Linux. Just tried it out, but I get a lot of 'Belated Tick' errors, although it's running on a Intel i7-4770K @ 3.5GHz and 16GB Ram.

**Comment by eliotcougar** [comment]
I've managed to run magneticod and magneticow on Windows... It has been throwing some exceptions because it's trying to open new connections too fast, before the old ones are closed, so I just added
`except ConnectionResetError:
    break
except OSError:
    break`
to the on_receivable function in dht.py

Now I see a lot of network traffic going, but the database does not seem to populate... The list of torrents is empty...

**Comment by ngosang** [comment]
I opened 2 PR for Windows compatibility. #32 #33

**Comment by eliotcougar** [comment]
@nsoang Yes!.. It works!..
adding socket return value and `except (ConnectionResetError, ConnectionRefusedError, OSError): continue` in on_receivable did the trick, but changing imports is not needed in my case, and only breaks everything...

**Comment by eliotcougar** [comment]
After running for 10 minutes it crashed with ValueError: too many file descriptors in select()
`Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Eliot\AppData\Roaming\Python\Python35\Scripts\magneticod.exe\__main__.py", line 9, in <module>
  File "C:\Users\Eliot\AppData\Roaming\Python\Python35\site-packages\magneticod\__main__.py", line 81, in main
    loop()
  File "C:\Users\Eliot\AppData\Roaming\Python\Python35\site-packages\magneticod\__main__.py", line 140, in loop
    keys_and_events = selector.select(timeout=TICK_INTERVAL)
  File "c:\python3\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "c:\python3\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()`

**Comment by ngosang** [comment]
> After running for 10 minutes it crashed with ValueError: too many file descriptors in select()

Already reported #38

**Comment by Koveras** [comment]
Is this the right place to suggest a step by step guide, so that noobs like me could get it running on windows?

**Comment by boramalper** [comment]
@Koveras Did you have a look at the instructions?

**Comment by MacgyverJohnson** [comment]
Pls support windows....throws exception 👍 
  `  RuntimeError: uvloop does not support Windows at the moment`
:'(

**Comment by deckar01** [comment]
I initially tried installing it on my Ubuntu WSL for Windows 10, but sqlite3 doesn't work right do to the way disk I/O is (not) implemented.

https://github.com/Microsoft/WSL/issues/2395

`setup.py` file shows that `uvloop` is behind a version check, but that it executes on the author's machine at publish time, so it's always going to be required in the egg provided by pypi.

https://github.com/boramalper/magnetico/blob/57d466a/magneticod/setup.py#L18

I believe `uvloop >= 0.8.0;platform_system!="Windows"` would resolve the platform dependency are install time.

https://stackoverflow.com/questions/6469508/is-it-possible-to-express-a-platform-specific-dependency-in-setup-py-without-bui

I cloned the repo, checked out the latest release tag, and ran `python setup.py install` to resolve the dependencies for the current architecture (windows) and it seems to work fine. I had to supply a random port number for `--node-addr` to get it to work, but maybe it was working and I was just impatient.
