### ISSUE TITLE
Random crash 

### ISSUE THREAD

**Issue by est42** [boramalper/magnetico#27]
Here is some random crash as well :/ 
Running it on clean standard debian jessie, python 3.5

INFO      magneticod v0.2.0 started
Traceback (most recent call last):
  File "/root/.local/bin/magneticod", line 11, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.4/site-packages/magneticod/__main__.py", line 61, in main
    arguments = parse_cmdline_arguments()
  File "/root/.local/lib/python3.4/site-packages/magneticod/__main__.py", line 187, in parse_cmdline_arguments
    formatter_class=argparse.RawDescriptionHelpFormatter
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

**Comment by boramalper** [comment]
Why did you close the issue? Could you identify the cause of the problem?

**Comment by est42** [comment]
Yes, for some reason python used old libraries instead of the new ones. After removing python 3.4 it worked like a charm

**Comment by boramalper** [comment]
Ah, understood. Glad that it's working now. =)
