### ISSUE TITLE
Implement garbage collector for sockets

### ISSUE THREAD

**Issue by ngosang** [boramalper/magnetico#38]
Peer should be destroyed after socket timeout or after several seconds without receiving data.
Now you are only destroying the peer if metadata is received
https://github.com/boramalper/magnetico/blob/master/magneticod/magneticod/__main__.py#L121
in other cases, number  of peers (and sockets) increases forever until you reach OS limit and process crash.

**Comment by ad-m** [comment]
@ngosang , please update issue title to respect content. Mention something like garbage collector for sockets.

**Comment by ngosang** [comment]
Done

**Comment by ad-m** [comment]
I think there is a related stack trace:

```
Traceback (most recent call last):
  File "/home/artur/.local/lib/python3.5/site-packages/magneticod/bittorrent.py", line 77, in on_receivable
    received = self.__socket.recv(8192)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./magneticod", line 9, in <module>
    load_entry_point('magneticod==0.2.0', 'console_scripts', 'magneticod')()
  File "/home/artur/.local/lib/python3.5/site-packages/magneticod/__main__.py", line 81, in main
    loop()
  File "/home/artur/.local/lib/python3.5/site-packages/magneticod/__main__.py", line 154, in loop
    key.fileobj.on_receivable()
  File "/home/artur/.local/lib/python3.5/site-packages/magneticod/bittorrent.py", line 87, in on_receivable
    self.when_error()
  File "/home/artur/.local/lib/python3.5/site-packages/magneticod/__main__.py", line 131, in on_peer_error
    peers[info_hash].remove(peer)
ValueError: list.remove(x): x not in list
```

**Comment by boramalper** [comment]
@ad-m It's related to #3, not this one.

**Comment by ad-m** [comment]
I believe this is a source of memory leak too...Memory continous grow up.

Here is graph of example magneticod session:
![dane](https://cloud.githubusercontent.com/assets/3618479/25558379/cca4056c-2d25-11e7-978a-887fe571598c.png)
The tests ends with:
```
Traceback (most recent call last):
  File "/home/artur/.local/lib/python3.5/site-packages/magneticod/bittorrent.py", line 87, in on_receivable
    received = self.__socket.recv(8192)
OSError: [Errno 9] Bad file descriptor
```
