### ISSUE TITLE
Crash with "Too many open files"

### ISSUE THREAD

**Issue by cez81** [boramalper/magnetico#47]
Version: v0.2.0
Python 3.5.3
Lubuntu 17.04

Ran fine for about 20min then crashed with the following stacktrace.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxxx/magniticod/lib/python3.5/site-packages/magneticod/__main__.py", line 225, in <module>
    sys.exit(main())
  File "/home/xxxx/magniticod/lib/python3.5/site-packages/magneticod/__main__.py", line 81, in main
    loop()
  File "/home/xxxx/magniticod/lib/python3.5/site-packages/magneticod/__main__.py", line 154, in loop
    key.fileobj.on_receivable()
  File "/home/xxxx/magniticod/lib/python3.5/site-packages/magneticod/dht.py", line 90, in on_receivable
    self.__on_ANNOUNCE_PEER_query(message, addr)
  File "/home/xxxx/magniticod/lib/python3.5/site-packages/magneticod/dht.py", line 207, in __on_ANNOUNCE_PEER_query
    self.when_peer_found(info_hash, peer_addr)
  File "/home/xxxx/magniticod/lib/python3.5/site-packages/magneticod/__main__.py", line 102, in on_peer_found
    peer = bittorrent.DisposablePeer(info_hash, peer_address)
  File "/home/xxxx/magniticod/lib/python3.5/site-packages/magneticod/bittorrent.py", line 32, in __init__
    self.__socket = socket.socket()
  File "/usr/lib/python3.5/socket.py", line 134, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
```

**Comment by ngosang** [comment]
Related #38
