### ISSUE TITLE
Error within flask trying to run magneticow

### ISSUE THREAD

**Issue by zapper59** [boramalper/magnetico#53]
I am trying to run magneticow on a windows machine running python 3.6.  It looks like it connects to magneticod's database, but when I load localhost:8080 in my browser I get the following error from inside of flask.

```
2017-04-26 19:00:52,405  INFO      Connecting to magneticod's database...`
2017-04-26 19:00:52,419  INFO      magneticow is ready to serve!
[2017-04-26 19:00:52,766] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\magneticow\magneticow.py", line 67, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\magneticow\magneticow.py", line 79, in home_page
    return flask.render_template("homepage.html", n_torrents=n_torrents)
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Brian\AppData\Roaming\Python\Python36\site-packages\magneticow\templates\homepage.html", line 20, in top-level template code
    Now with {{ "{:,}".format(n_torrents) }} torrents available !
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by schmitzkr** [comment]
I recieve the same typeerror
`2017-04-26 18:06:26,251  INFO      Connecting to magneticod's database...
2017-04-26 18:06:26,252  INFO      magneticow is ready to serve!
::1 - - [2017-04-26 18:06:31] "GET / HTTP/1.1" 401 264 0.000632
[2017-04-26 18:06:33,869] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kyle/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kyle/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kyle/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kyle/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kyle/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kyle/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kyle/.local/lib/python3.5/site-packages/magneticow/magneticow.py", line 67, in decorated
    return f(*args, **kwargs)
  File "/home/kyle/.local/lib/python3.5/site-packages/magneticow/magneticow.py", line 79, in home_page
    return flask.render_template("homepage.html", n_torrents=n_torrents)
  File "/home/kyle/.local/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/kyle/.local/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/kyle/.local/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/kyle/.local/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kyle/.local/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/kyle/.local/lib/python3.5/site-packages/magneticow/templates/homepage.html", line 20, in top-level template code
    Now with {{ "{:,}".format(n_torrents) }} torrents available !
TypeError: unsupported format string passed to NoneType.__format__`

**Comment by boramalper** [comment]
I guess you were running it for the first time and database was empty. Try running **magneticod** for a while until the database is populated.

Nevertheless, it's a bug that we need to address (user should be informed).

**Comment by boramalper** [comment]
We no longer use Python so closing the issue. =)
