### ISSUE TITLE
magneticod crashing on FreeBSD

### ISSUE THREAD

**Issue by ciaby** [boramalper/magnetico#80]
This is what I get when it's left running for a bit:

```
2017-05-23 11:17:38,951  WARNING   Belated TICK! (Δ = 5)
2017-05-23 11:17:44,973  WARNING   Belated TICK! (Δ = 5)
2017-05-23 11:17:50,994  WARNING   Belated TICK! (Δ = 5)
Traceback (most recent call last):
  File "/usr/local/bin/magneticod", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/magneticod/__main__.py", line 81, in main
    loop()
  File "/usr/local/lib/python3.6/site-packages/magneticod/__main__.py", line 160, in loop
    key.fileobj.on_receivable()
  File "/usr/local/lib/python3.6/site-packages/magneticod/bittorrent.py", line 122, in on_receivable
    self.__on_bt_handshake(self.__incoming_buffer[:68])
  File "/usr/local/lib/python3.6/site-packages/magneticod/bittorrent.py", line 193, in __on_bt_handshake
    msg_dict_dump
TypeError: not all arguments converted during bytes formatting
```
Any clue on how to debug it?

**Comment by boramalper** [comment]
Hey @ciaby, thanks for reporting it. =)

It's due to a bug in the Python 3.6 and 3.6.1, which has nothing to do with us, and causes the crash.

I was against developing a workaround -since I stubbornly insisted that it's not our fault- but since many people encountered that, I think I'll fix it soon, hopefully before Python 3.6.2 which fixes that.

**Comment by boramalper** [comment]
The bug: http://bugs.python.org/issue29714

**Comment by ciaby** [comment]
Oh, ok :) Should I switch to Python 3.5 in the meantime?

**Comment by boramalper** [comment]
Sure, if you can!

**Comment by ciaby** [comment]
Yep, I just switched to 3.5. The Belated TICK problem is still there... (delta is always 5 seconds).
What could be?

**Comment by ad-m** [comment]
@ciaby , this is another issue. See #11.

**Comment by richardkiss** [comment]
I believe issue29714 is fixed by https://github.com/boramalper/magnetico/pull/74

**Comment by oscarcarlsson** [comment]
I've successfully started magneticod on FreeBSD 11, I think it's safe to mark this as resolved.
