### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by Glandos** [boramalper/magnetico#91]
It should be good for a new software to have IPv6 support.
I personnally don't have time to code on this, but I can perform some tests if needed.

**Comment by mweinelt** [comment]
This is currently where it breaks when listening on an IPv6 address:

```
2017-08-03 02:00:57,301  INFO      magneticod v0.6.0 started
2017-08-03 02:00:57,362  INFO      uvloop is in use
2017-08-03 02:00:57,372  INFO      SybilNode 968389752305165278AAA02FC34C92A7DED29669 initialized!
2017-08-03 02:00:57,375  INFO      SybliNode is launched on ('::', 42345)!
2017-08-03 02:00:57,375  ERROR     Unhandled exception in event loop
Traceback (most recent call last):
  File "uvloop/handles/udp.pyx", line 339, in uvloop.loop.__uv_udp_on_receive (uvloop/loop.c:105828)
  File "uvloop/handles/udp.pyx", line 241, in uvloop.loop.UDPTransport._on_receive (uvloop/loop.c:104744)
  File "/home/magnetico/magnetico/magneticod/magneticod/dht.py", line 139, in datagram_received
    self.__on_GET_PEERS_query(message, addr)
  File "/home/magnetico/magnetico/magneticod/magneticod/dht.py", line 181, in __on_GET_PEERS_query
    info_hash[:15] + self.__true_id[:5], transaction_id, self.__calculate_token(addr, info_hash)
  File "/home/magnetico/magnetico/magneticod/magneticod/dht.py", line 339, in __calculate_token
    checksum = zlib.adler32(b"%s%s%d%s" % (self.__token_secret, socket.inet_aton(addr[0]), addr[1], info_hash))
OSError: illegal IP address string passed to inet_aton
```

I'm not sure how much IPv4 is tied into the protocol.

**Comment by snaakey** [comment]
+1

**Comment by centralhardware** [comment]
is this python version? what about actual go version?

**Comment by kescherCode** [comment]
The Go version also doesn't support it currently, iirc.
