### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by dim-geo** [boramalper/magnetico#94]
Hello,

when starting magneticod 0.5 for the first time on armhf architecture (testing debian branch),

```
magneticod -d
2017-06-09 18:01:43,458  INFO      magneticod v0.5.0 started
2017-06-09 18:01:43,469  INFO      uvloop is in use
2017-06-09 18:01:43,698  INFO      SybilNode 9BAF683C6E2868CDA972B40F1A254924DE4F947C on ('0.0.0.0', 0) initialized!
2017-06-09 18:01:45,535  DEBUG     fetch metadata task count: 0
2017-06-09 18:01:45,537  DEBUG     asyncio task count: 2
2017-06-09 18:01:46,544  DEBUG     fetch metadata task count: 0
2017-06-09 18:01:46,545  DEBUG     asyncio task count: 2
2017-06-09 18:01:47,293  ERROR     Unhandled exception in event loop
Traceback (most recent call last):
  File "/home/simpleuser/.local/lib/python3.5/site-packages/magneticod/bencode.py", line 31, in dumps
    return magneticod.bencoder.dumps(obj)
OverflowError: Python int too large to convert to C long
```
Another exception happens, probably related after the first one:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvloop/handles/udp.pyx", line 339, in uvloop.loop.__uv_udp_on_receive (uvloop/loop.c:105828)
  File "uvloop/handles/udp.pyx", line 241, in uvloop.loop.UDPTransport._on_receive (uvloop/loop.c:104744)
  File "/home/simpleuser/.local/lib/python3.5/site-packages/magneticod/dht.py", line 132, in datagram_received
    self.__on_GET_PEERS_query(message, addr)
  File "/home/simpleuser/.local/lib/python3.5/site-packages/magneticod/dht.py", line 175, in __on_GET_PEERS_query
    b"token": self.__calculate_token(addr, info_hash)
  File "/home/simpleuser/.local/lib/python3.5/site-packages/magneticod/bencode.py", line 33, in dumps
    raise BencodeEncodingError()
magneticod.bencode.BencodeEncodingError
2017-06-09 18:01:47,328  ERROR     Unhandled exception in event loop
```

**Comment by Maverik44** [comment]
I am seeing this error as of now.

> 2017-06-15

 17:44:10,747  ERROR     Unhandled exception in event loop
Traceback (most recent call last):
  File "uvloop/handles/udp.pyx", line 339, in uvloop.loop.__uv_udp_on_receive (uvloop/loop.c:105828)
  File "uvloop/handles/udp.pyx", line 241, in uvloop.loop.UDPTransport._on_receive (uvloop/loop.c:104744)
  File "/usr/local/lib/python3.5/dist-packages/magneticod/dht.py", line 137, in datagram_received
    if isinstance(message.get(b"r"), dict) and type(message[b"r"].get(b"nodes")) is bytes:
AttributeError: type object 'StopIteration' has no attribute 'get'

**Comment by Maverik44** [comment]
This error seems to only bug me on version v0.6.0.
When I went back to version v0.5.0 everything works.
